### ISSUE TITLE
Documentation for the Cordova implementation

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#137]
Explain at rogerthat.net how developers can create cordova-based brandings
Also list the plugins that are added by default

**Comment by RubenMattan** [comment]
https://github.com/rogerthat-platform/rogerthat-android-client/blob/cordova/specs/cordova.md

**Comment by lucasvanhalst** [comment]
http://www.rogerthat.net/developers/cordova-based-brandings/
