### ISSUE TITLE
Email field not visible on registration activity on android 7

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-android-client#157]
When focusing the email field, the app doesn't shrink as it used to and the keyboard is show over the rest of the activity
![screenshot_20170508-135305](https://cloud.githubusercontent.com/assets/6652304/25804515/6b2d9b1c-33fc-11e7-8897-dfe1a457da8f.png)

**Comment by RubenMattan** [comment]
Simulator with api 24/25 does not have this issue

**Comment by lucasvanhalst** [comment]
Couldn't reproduce this on my phone either... Maybe it was a bug with the swiftkey keyboard I have installed
