### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-android-client#16]
Would be nice to have. 

https://uncodin.github.io/bypass/

**Comment by RubenMattan** [comment]
other options:
- https://github.com/commonsguy/cwac-anddown
- https://github.com/mukeshsolanki/MarkdownView-Android
- https://github.com/fiskurgit/MarkdownView

**Comment by RubenMattan** [comment]
- FriendsThreadActivity
- NewsActivity
- ServiceMessageDetailActivity (only when not branded or when native)
