### ISSUE TITLE
Android client gets in an infinite loop if the ReponseTO can not be parsed

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#161]
Eg.

`{"settings":{"geoLocationSamplingIntervalCharging":900,"operatingVersion":0,"useGPSCharging":true,"recordPhoneCallsDays":31,"xmppReconnectInterval":900,"geoLocationTrackingDays":127,"geoLocationSamplingIntervalBattery":900,"geoLocationTrackingTimeslot":[0,86399],"geoLocationTracking":true,"version":3,"recordPhoneCallsTimeslot":[0,86399],"backgroundFetchTimestamps":[25200],"useGPSBattery":false,"wifiOnlyDownloads":null,"recordGeoLocationWithPhoneCalls":true,"recordPhoneCalls":false}}`

The SettingsTO in the response contained wifiOnlyDownloads = null, instead of a boolean. The client will then retry the same call over and over again.

Relates to rogerthat-platform/mcfw/issues/4

**Comment by RubenMattan** [comment]
@bart-at-mobicage how would you fix this?

**Comment by bart-at-mobicage** [comment]
Dont know if the app crashes... I'd just prevent the app from crashing. Something like this.

```
} catch (IncompleteMessageException e) {
    L.bug(e);
    return;
}
```

**Comment by RubenMattan** [comment]
So we just ack the message?

**Comment by RubenMattan** [comment]
Current implementation:
https://github.com/rogerthat-platform/rogerthat-android-client/blob/master/rogerthat/src/main/java/com/mobicage/rpc/http/HttpProtocol.java#L253

**Comment by bart-at-mobicage** [comment]
I think we have to, else the server will keep on sending the response and will keep telling the phone that there are more items in the backlog

**Comment by RubenMattan** [comment]
iOS implementation:
https://github.com/rogerthat-platform/rogerthat-ios-client/blob/master/src/MCTRPCProtocol.m#L159
