### ISSUE TITLE
Payments: Splash screens

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-android-client#182]
~- [ ] Modify prepare_build so that it copies the 'resources/android' folder from the apps (like rogerthat-payment)~
~- [ ] Modify prepare_build so that it reads config.xml from apps and gathers <platform name="android"> and copies all properties inside to the generated config.xml~
- [x] Refactor prepare_build so that it gathers the plugin dependencies from config.xml instead of hardcoding them in cordova.py. Ensure the versions match the allowed versions.
- [ ] Let designer create appropriate splash screens for rogerthat-payment and place them in the rogerthat-payment repo

**Comment by RubenMattan** [comment]
We need to create our own splash screen plugin because we need more then 1 splash screen.

**Comment by RubenMattan** [comment]
reading plugin dependencies from config.xml is ok but we still need the hardcoded stuff for our custom plugins
