### ISSUE TITLE
Every avatar should be clickable

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#189]
Geert Audenaert, [Jul 11, 2017, 2:07 PM]:
> Any reference to a user should be clickable
> To show contact screen
> Or to invite him to your friends

**Comment by RubenMattan** [comment]
@bart-at-mobicage What avatars are not clickable?

**Comment by RubenMattan** [comment]
We only need to implement this when rogered news is listing everyone

**Comment by RubenMattan** [comment]
Just investigated and this is already the done
