### ISSUE TITLE
Don't show back button in app-wide pin setup screen

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#218]
![image](https://user-images.githubusercontent.com/17762105/29403018-4647d29c-8337-11e7-9dee-a6f466ac13da.png)

**Comment by RubenMattan** [comment]
Already implemented in https://github.com/rogerthat-platform/rogerthat-android-client/commit/d722ce7b38ec5154605454b392f2f80947d7265b
