### ISSUE TITLE
New message checks recipients without selecting them

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#242]
There avatar was not show at the top of the screen but there was a checkmark next to their name...

**Comment by lucasvanhalst** [comment]
Are there any steps to reproduce this? Because it works fine for me

**Comment by RubenMattan** [comment]
No idea, @FastGeert how can we reproduce this?

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#47
