### ISSUE TITLE
Make it possible to show TOS URL for enterprise apps

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-android-client#260]
Maybe just check if the URL is empty in build.yaml and if not, show it instead of checking if the app is an enterprise app and hiding it

**Comment by RubenMattan** [comment]
Don't understand what i need to do for this issue

**Comment by lucasvanhalst** [comment]
https://github.com/rogerthat-platform/rogerthat-android-client/blob/6f014aea4e305df0702fa64061124ebfd5df63f2/rogerthat/src/main/java/com/mobicage/rogerthat/registration/RegistrationActivity2.java#L333-L339

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#15
