### ISSUE TITLE
App page in Play Store

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#264]
Eg. https://play.google.com/store/apps/details?id=com.mobicage.rogerthat.be.veurne&hl=nl

<img width="667" alt="screen shot 2017-10-12 at 13 54 54" src="https://user-images.githubusercontent.com/17762105/31494742-f7c3e7a6-af54-11e7-84c2-6eed31c109f9.png">

- [ ] the website should be www.onzestadapp.be for city apps (not www.rogerthat.net)
- [ ] the contact email address should be info@onzestadapp.be (not info@mobicage.com)
- [ ] should be set according to the app's country

**Comment by RubenMattan** [comment]
Issue was fixed
