### ISSUE TITLE
Reach keeps spinning

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#277]
Probably happens when the connection has been lost. When killing the app and restarting again, the reach is shown

**Comment by RubenMattan** [comment]
1. Simulated no network: no network header appeared and reach kept spinning
2. Enabled network: Header disappeared and reach appeared after 2s or so

So without knowing exactly what happened i cannot reproduce this

**Comment by lucasvanhalst** [comment]
leaving app in background and re-opening after a day also worked

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#45
