### ISSUE TITLE
Improve image compression

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-android-client#279]
If my camera takes a 4000x3000 picture, but a max of 2MB is set, it will still be a 4000x3000 picture but it will look terrible because of excessive compression.
Either add a 'maxResolution' property to the photo widget, or automatically reduce the resolution to improve image quality.

the 'quality' property also doesn't seem to work very well, if I enter 2000000 (+-2MB) it will compress the picture to 2.8MB

**Comment by RubenMattan** [comment]
File size can indeed be more then specified, however we do shrink width and height

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#12
