### ISSUE TITLE
Build setting to limit supported languages in an app

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#283]
Make it configurable in `build.yaml` to limit supported languages. 
Eg. only English. Or only Dutch and French.

https://docs.greenitglobe.com/ThreeFold/proj_onboarding_tools/issues/113

**Comment by RubenMattan** [comment]
There is an easy way to do this (https://developer.android.com/studio/build/shrink-code.html => resConfigs)
However the default language will always be present. so ```resConfigs "fr"``` will have en and fr

**Comment by bart-at-mobicage** [comment]
> However the default language will always be present. so resConfigs "fr" will have en and fr

can we copy the content of the values-fr folder into the default values? to "force change" the default language to fr?
