### ISSUE TITLE
Add news related methods for cordova/html5 apps

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#305]
`rogerthat.news.list(params, resultHandler, errorHandler)`
  - `params` can contain `cursor` (string), `limit` (int)
  - the response given via the resultHandler contains `result` and `cursor`
    - `cursor` is a string
    - `result` is an array of news items
      - a news item (AppNewsItemTO) contains: `id`, `partial`, `title`, `message`, `image_url`...
      - when `partial` is `true` then `title`, `message`, `image_url`... will be `undefined`.  The complete news item will be downloaded async and delivered via `rogerthat.callbacks.newsReceived(newsItems)`.

**Comment by bart-at-mobicage** [comment]
@RubenMattan, I forgot to push `db_sql.xml`. Just pushed it now.

**Comment by RubenMattan** [comment]
We also need the following methods i guess:
- news.count
- news.read
- news.save
- news.stats
- news.reindex

**Comment by RubenMattan** [comment]
For now i only implemented:
- count
- get
- list
- newsReceived callback

**Comment by bart-at-mobicage** [comment]
I just saw your comments. 

I was thinking that `news.list`, `newsReceived` and `badgeUpdated` would be enough (for now).
If new news items arrive, `badgeUpdated` will be called so the branding can call `news.list` again (which will download partial news async and call `newsReceived`).

**Comment by RubenMattan** [comment]
How does the branding reset the news badge then?

**Comment by bart-at-mobicage** [comment]
I was thinking to let them open the news feed, then the news will be read.

Let's check with @FastGeert to see how far we need to go with this implementation. Maybe it's enough in phase 1 to go for a readonly API.

**Comment by RubenMattan** [comment]
> We will only implement the things we need right now.
