### ISSUE TITLE
Change the "Transmitting..." text when there's nothing transmitting

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#338]
When a service menu item is pressed or a button of a flow step, then a popup with a spinner and the text "Transmitting..." is shown. This is not logical for the user, because the result is the flow is not yet transmitted.

Remove the text. Or if this result is ugly, then change the text to "Processing..."

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#8
