### ISSUE TITLE
Uploaded picture is ridiculously small

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#352]
2 examples of pictures uploaded with the report card of be-zandhoven

![image](https://user-images.githubusercontent.com/17762105/39038744-865e799e-4484-11e8-84ea-f385c7edb26b.png) ![image](https://user-images.githubusercontent.com/17762105/39038757-8abef9e6-4484-11e8-899f-af93d36e05c3.png)

Mobile info:
- hardware model: SM-A320FL (Samsung Galaxy A3 2017)
- os version: 24
- app version: 2.1.3864

**Comment by RubenMattan** [comment]
Maybe this will help https://stackoverflow.com/questions/28424942/decrease-image-size-without-losing-its-quality-in-android

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#37
