### ISSUE TITLE
News feed doesn't show notifications in Android app

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#361]
People of Nazareth mention that they don't see push notifications when the city broadcasts a news item. Steven and Maureen don't receive them as well.

**Comment by lucasvanhalst** [comment]
The calls arrive at the phone, but no push notification is generated.

So either:

- the news item already exists in the phone db (that can't be the case)
- the broadcast type 'Nieuws' is disabled (it isn't)
- the friend doesn't exist (also not possible since it's auto-connected)

**Comment by RubenMattan** [comment]
The news item was sent silently
