### ISSUE TITLE
The FULL_WIDTH_HEADER property is not respected in the menu sidebar

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#45]

**Comment by RubenMattan** [comment]
@bart-at-mobicage What app needs this?

**Comment by bart-at-mobicage** [comment]
All apps with `FULL_WIDTH_HEADERS=true` probably have more margin then intended. 

Or apps with `FULL_WIDTH_HEADERS=false` have less margin then intended. Depending on the implementation.

**Comment by RubenMattan** [comment]
Can you give me 1 app where the current implementation is not good

**Comment by RubenMattan** [comment]
We will continue this when there is an app that needs this.
