### ISSUE TITLE
Picture corners not properly rounded

### ISSUE THREAD

**Issue by FastGeert** [rogerthat-platform/rogerthat-android-client#57]
Test scenario:
- Installed merchtem app via Google Play (version 1.0.2499.A)
- Opened news directly after registration

![image](https://cloud.githubusercontent.com/assets/15246294/20621227/d45dbafc-b2fd-11e6-91a7-8603df3206c1.png)

**Comment by RubenMattan** [comment]
could not reproduce...

**Comment by FastGeert** [comment]
Thats too easy.

**Comment by RubenMattan** [comment]
![screen shot 2016-11-29 at 12 01 51](https://cloud.githubusercontent.com/assets/1122760/20707422/b83cee0c-b62b-11e6-99d8-5b615840f86d.png)
![2016-11-29 11 00 46](https://cloud.githubusercontent.com/assets/1122760/20707430/bf41d276-b62b-11e6-9099-fd4ea6e7fa69.png)

**Comment by bart-at-mobicage** [comment]
2nd issue (defined in the comment) is fixed. 
1st one still needs to be investigated.
