### ISSUE TITLE
Daily sync of the news feed

### ISSUE THREAD

**Issue by FastGeert** [rogerthat-platform/rogerthat-android-client#60]
Every day between 19:30 and 20:30 we should check if there are new news items. We should update the badge number and create a silent notification with "xxx new news items".

Only if no other notifications are already present.

**Comment by bart-at-mobicage** [comment]
Reopened because the notification and badge stuff are not implemented

**Comment by RubenMattan** [comment]
Notification was already implemented and i just updated the badge count after syncing.
