### ISSUE TITLE
The Agenda branding shows an empty screen in some apps

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#76]
It's shown on Android in Berlare, but not in Oudenaarde, OSA Demo, Lochristi.
It's shown on iOS.

**Comment by lucasvanhalst** [comment]
I could not reproduce this. What device was used?

**Comment by lucasvanhalst** [comment]
Made some changes that I think could be the cause but I'm not sure... 

https://github.com/our-city-app/oca-backend/commit/472327c?w=1
