### ISSUE TITLE
Don't show empty chat description in ChatInfoActivity

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#83]
When a user starts a group conversation with more than 15 members, a chat is created with an empty description. In the ChatInfoActivity, don't show the "Description" label if the description is empty.

**Comment by RubenMattan** [comment]
https://github.com/rogerthat-platform/rogerthat-android-client/pull/84/commits/99fd0971f93a2984ef34bd3a1e451b5ee3f15e9c
